### ISSUE TITLE
Introduce performance measurement tool for VSCode

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-perf#1]
Introduce performance measurement tool for VSCode for following run times

- Desktop
- Web
  - Empty default
  - GitHub PR
  - Deeplink to GitHub file
  - Deeplink to GitHub notebook editor

**Comment by bpasero** [comment]
https://github.com/bpasero/vscode-bisect/commit/3d6675d2f870747389da88405501157edd91b66a adds support for web to `vscode-bisect` 🎉

**Comment by bpasero** [comment]
I think we can go ahead and close this. I am planning to add more scenarios on-demand and not up-front.
